#!/bin/bash

# run this script from the root 'csure' directory, e.g., {.../csure} ./stuff/format-all
# it uses clang-format to format all .cc and .h files in our whole source tree

find . \( -name '*.cc' -o -name '*.h' \) -execdir clang-format -style=file -i {} \;

