#!/bin/bash

# Run this script to use clang-format to format all .cpp and .h files in the
# source tree below the pwd. It searchs up the path for a '.clang-format' file
# to read its settings from.
find . \( -name '*.cpp' -o -name '*.h' \) -execdir clang-format -style=file -i {} \;

